openapi: 3.1.0
info:
  title: ComicBook API
  version: 1.0.0
  description: |
    A REST API for browsing, managing, and rating comic books. 
    Provides user authentication, role-based authorization, and full CRUD capabilities 
    for comics, genres, ratings, and user reading lists.
servers:
  - url: http://localhost:8080
    description: Local development server
  - url: https://your-render-app.onrender.com
    description: Render deployment environment
paths:
  /api/auth/signup:
    post:
      tags:
        - auth
      summary: Register a new user
      description: Creates a new user account using email and password.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '201':
          description: User successfully registered
  /api/auth/login:
    post:
      tags:
        - auth
      summary: Login and receive a JWT token
      description: Authenticates a user and returns an access token for future requests.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Login successful — returns JWT access token
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
  /api/auth/logout:
    post:
      tags:
        - auth
      summary: Logout the user
      description: |
        Invalidates the currently authenticated user's JWT token.  
        Requires a valid Bearer token.
      security:
        - bearerAuth: []
      responses:
        '200':
          description: User logged out successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Logged out successfully. Token invalidated.
        '400':
          description: No token provided or invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: You have not logged in or provided a token.
  /api/comics:
    get:
      tags:
        - comics
      summary: Retrieve all comics
      responses:
        '200':
          description: List of comics
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Comic'
    post:
      tags:
        - comics
      summary: Create a new comic (Admin only)
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - title
                - author
                - publisher
                - releaseYear
                - genre
              properties:
                title:
                  type: string
                author:
                  type: string
                publisher:
                  type: string
                releaseYear:
                  type: integer
                description:
                  type: string
                genre:
                  type: string
      responses:
        '201':
          description: Comic created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Comic'
  /api/comics/{id}:
    get:
      tags:
        - comics
      summary: Get a comic by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Comic details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Comic'
    put:
      tags:
        - comics
      summary: Update an existing comic (Admin only)
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                author:
                  type: string
                publisher:
                  type: string
                releaseYear:
                  type: integer
                description:
                  type: string
                genre:
                  type: string
      responses:
        '200':
          description: Comic updated successfully
    delete:
      tags:
        - comics
      summary: Delete a comic (Admin only)
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Comic deleted successfully
  /api/genres:
    get:
      tags:
        - genres
      summary: Retrieve all genres with their comics
      responses:
        '200':
          description: List of genres with their associated comics
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Genre'
    post:
      tags:
        - genres
      summary: Create a genre (Admin only)
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - genre
              properties:
                genre:
                  type: string
      responses:
        '201':
          description: Genre created successfully
  /api/genres/{id}:
    get:
      tags:
        - genres
      summary: Get a genre by ID
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: Genre details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Genre'
    put:
      tags:
        - genres
      summary: Update a genre (Admin only)
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                genre:
                  type: string
      responses:
        '200':
          description: Genre updated successfully
    delete:
      tags:
        - genres
      summary: Delete a genre (Admin only)
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
      responses:
        '204':
          description: Genre deleted successfully
  /api/ratings:
    get:
      tags:
        - ratings
      summary: Retrieve all ratings
      responses:
        '200':
          description: List of ratings with user and comic info
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Rating'
    post:
      tags:
        - ratings
      summary: Create a rating (Authenticated users only)
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - comicId
                - rating
              properties:
                comicId:
                  type: integer
                rating:
                  type: integer
                description:
                  type: string
      responses:
        '201':
          description: Rating created successfully
  /api/ratings/{id}:
    get:
      tags:
        - ratings
      summary: Get a rating by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Rating details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Rating'
    put:
      tags:
        - ratings
      summary: Update a rating (Authenticated users only)
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                comicId:
                  type: integer
                rating:
                  type: integer
                description:
                  type: string
      responses:
        '200':
          description: Rating updated successfully
    delete:
      tags:
        - ratings
      summary: Delete a rating (Authenticated users only)
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
      responses:
        '204':
          description: Rating deleted successfully
  /api/reading-list:
    get:
      tags:
        - reading-list
      summary: Get reading list for the logged-in user
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Reading list items for the authenticated user
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ReadingEntry'
    post:
      tags:
        - reading-list
      summary: Add a comic to the reading list
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - comicId
              properties:
                comicId:
                  type: integer
      responses:
        '201':
          description: Comic added to reading list
  /api/reading-list/{id}:
    get:
      tags:
        - reading-list
      summary: Get a reading list entry by ID
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Reading entry details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReadingEntry'
    delete:
      tags:
        - reading-list
      summary: Remove a comic from the reading list
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Entry removed from reading list
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Comic:
      type: object
      properties:
        id:
          type: integer
          example: 13
        title:
          type: string
          example:
            Spider-Man: Into the Spider-Verse
        author:
          type: string
          example: Brian Michael Bendis
        publisher:
          type: string
          example: Marvel Comics
        releaseYear:
          type: integer
          example: 2018
        genre:
          type: string
          example: Superhero
        rating:
          type: number
          example: 4.9
        description:
          type: string
          example: Miles Morales becomes the Spider-Man of his reality...
    Genre:
      type: object
      properties:
        id:
          type: integer
          example: 13
        genre:
          type: string
          example: Action
        comics:
          type: array
          items:
            type: object
            properties:
              id:
                type: integer
                example: 14
              title:
                type: string
                example:
                  Batman: Year One
              author:
                type: string
                example: Frank Miller
              publisher:
                type: string
                example: DC Comics
              releaseYear:
                type: integer
                example: 1987
              description:
                type: string
                example: Bruce Wayne returns to Gotham City and becomes Batman...
    User:
      type: object
      properties:
        id:
          type: integer
          example: 12
        email:
          type: string
          example: test@example.com
        role:
          type: string
          enum:
            - USER
            - ADMIN
          example: USER
    Rating:
      type: object
      properties:
        id:
          type: integer
          example: 10
        rating:
          type: integer
          example: 5
        description:
          type: string
          example: Amazing! I would recommend
        createdAt:
          type: string
          format: date-time
        userId:
          type: integer
        comicId:
          type: integer
        author:
          $ref: '#/components/schemas/User'
        comic:
          type: object
          properties:
            id:
              type: integer
            title:
              type: string
            author:
              type: string
            publisher:
              type: string
            releaseYear:
              type: integer
            description:
              type: string
    ReadingEntry:
      type: object
      properties:
        id:
          type: integer
          example: 10
        userId:
          type: integer
          example: 13
        comicId:
          type: integer
          example: 14
        createdAt:
          type: string
          format: date-time
        comic:
          type: object
          properties:
            id:
              type: integer
            title:
              type: string
            author:
              type: string
            publisher:
              type: string
            releaseYear:
              type: integer
            description:
              type: string
